name: Build All Plugins

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Build EmoteGrid
        run: dotnet build EmoteGrid/EmoteGrid.csproj -c Release --output ./artifacts/EmoteGrid

      - name: Build NameplateToggle
        run: dotnet build NameplateToggle/NameplateToggle.csproj -c Release --output ./artifacts/NameplateToggle



      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AllPlugins
          path: ./artifacts/
